apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/argocon-2022-workshop/demo-app
  newName: ghcr.io/rbreeze/demo-app
  newTag: 1afef9a
  
